### ISSUE TITLE
Timestamp of frames at client

### ISSUE THREAD

**Issue by jax79sg** [oddity-ai/oddity-rtsp#20]
Hi, we are re-streaming incoming rtsp and video sources into internal clients, which will use the frames for machine learning inference, is it possible for the internal clients to retrieve timestamps of frames so they can be correlated at the analytics level?

**Comment by gerwin3** [comment]
I think the timestamps should be the same (though I'm not 100% sure how ffmpeg handles this internally). Are you seeing different DTS/PTS from the original stream when restreaming?
