### ISSUE TITLE
Error building 

### ISSUE THREAD

**Issue by fgadaleta** [oddity-ai/oddity-rtsp#21]
error[E0432]: unresolved import `ffmpeg::format::register_all`
 --> /home/frag/.cargo/registry/src/github.com-1ecc6299db9ec823/video-rs-0.1.8/src/init.rs:6:5
  |
6 |     register_all,
  |     ^^^^^^^^^^^^
  |     |
  |     no `register_all` in `format`
  |     help: a similar name exists in the module: `register_t`

error[E0599]: no method named `codec` found for reference `&StreamMut<'_>` in the current scope
   --> /home/frag/.cargo/registry/src/github.com-1ecc6299db9ec823/video-rs-0.1.8/src/encode.rs:363:8
    |
363 |       .codec()
    |        ^^^^^ method not found in `&StreamMut<'_>`

error[E0599]: no method named `codec` found for struct `Stream` in the current scope
   --> /home/frag/.cargo/registry/src/github.com-1ecc6299db9ec823/video-rs-0.1.8/src/mux.rs:316:19
    |
316 |         if stream.codec().id() == AvCodecId::H264 {
    |                   ^^^^^ method not found in `Stream<'_>`

Some errors have detailed explanations: E0432, E0599.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `video-rs` due to 3 previous errors

**Comment by gerwin3** [comment]
Yeah this is related to an issue with [video-rs](https://github.com/oddity-ai/oddity-video) that I'm currently working on. Will be fixed soon. Using ffmpeg 4 should work for now.
